// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"caCert": {
			Default:     "",
			Description: "CACert is the Kafka broker's certificate.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"clientCert": {
			Default:     "",
			Description: "ClientCert is the Kafka client's certificate.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"clientID": {
			Default:     "conduit-connector-kafka",
			Description: "ClientID is a unique identifier for client connections established by\nthis connector.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"clientKey": {
			Default:     "",
			Description: "ClientKey is the Kafka client's private key.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"groupID": {
			Default:     "",
			Description: "GroupID defines the consumer group id.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"insecureSkipVerify": {
			Default:     "",
			Description: "InsecureSkipVerify defines whether to validate the broker's certificate\nchain and host name. If 'true', accepts any certificate presented by the\nserver and any host name in that certificate.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"readFromBeginning": {
			Default:     "",
			Description: "ReadFromBeginning determines from whence the consumer group should begin\nconsuming when it finds a partition without a committed offset. If this\noptions is set to true it will start with the first message in that\npartition.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"retryGroupJoinErrors": {
			Default:     "true",
			Description: "RetryGroupJoinErrors determines whether the connector will continually retry on group join errors.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"retryLeaderErrors": {
			Default:     "true",
			Description: "RetryLeaderErrors determines whether the connector will continually retry on leader errors.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"saslMechanism": {
			Default:     "",
			Description: "Mechanism configures the connector to use SASL authentication. If\nempty, no authentication will be performed.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"PLAIN", "SCRAM-SHA-256", "SCRAM-SHA-512"}},
			},
		},
		"saslPassword": {
			Default:     "",
			Description: "Password sets up the password used with SASL authentication.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"saslUsername": {
			Default:     "",
			Description: "Username sets up the username used with SASL authentication.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"servers": {
			Default:     "",
			Description: "Servers is a list of Kafka bootstrap servers, which will be used to\ndiscover all the servers in a cluster.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"tls.enabled": {
			Default:     "",
			Description: "TLSEnabled defines whether TLS is needed to communicate with the Kafka cluster.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"topic": {
			Default:     "",
			Description: "Topic {WARN will be deprecated soon} the kafka topic to read from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"topics": {
			Default:     "",
			Description: "Topics is a comma separated list of Kafka topics to read from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
