name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test connector with Kafka
        run: make test-kafka GOTEST_FLAGS="-v -count=1"

      - name: Test connector with Redpanda
        run: make test-redpanda GOTEST_FLAGS="-v -count=1"
